# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, base64Bytestring, caseInsensitive, exceptions
, fetchgit, QuickCheck, tasty, tastyQuickcheck, text, textIcu, time
}:

cabal.mkDerivation (self: {
  pname = "email-header";
  version = "0.3.0";
  src = fetchgit {
    url = "https://github.com/4z3/email-header";
    sha256 = "f8e77302594d8ff163a5df75dd886f9932ef9d1a084f79c0393b48fcb2a51eb4";
    rev = "3ba16e71cf1fff92fd86199f893d89a40ca1275d";
  };
  buildDepends = [
    attoparsec base64Bytestring caseInsensitive exceptions text textIcu
    time
  ];
  testDepends = [
    caseInsensitive QuickCheck tasty tastyQuickcheck text time
  ];
  jailbreak = true;
  meta = {
    homepage = "http://github.com/knrafto/email-header";
    description = "Parsing and rendering of email and MIME headers";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
