# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, base64Bytestring, blazeBuilder, fetchgit, filepath, hspec
, random, sendmail ? "sendmail", text
}:

cabal.mkDerivation (self: {
  pname = "mime-mail";
  version = "0.4.6.2";
  src = fetchgit {
    url = "https://github.com/4z3/mime-mail";
    sha256 = "fa2ecb7ca0f71513a8f4dde897ff910d94a205c4a81c6b5e107e4712438b0446";
    rev = "3d0f060fb4c58b69c72ce3b4911bff32df7329a7";
  };
  buildDepends = [
    base64Bytestring blazeBuilder filepath random text
  ];
  testDepends = [ blazeBuilder hspec text ];
  configureFlags = "--ghc-option=-DMIME_MAIL_SENDMAIL_PATH=\"${sendmail}\"";
  meta = {
    homepage = "http://github.com/snoyberg/mime-mail";
    description = "Compose MIME email messages";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
