# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, HUnit, testFramework, testFrameworkHunit, time }:

cabal.mkDerivation (self: {
  pname = "friendly-time";
  version = "0.3";
  sha256 = "10p78qbb1c87d0ag6cwc7blgwaw8r5sbs00gp5qg3sh9x7n9l3nj";
  buildDepends = [ time ];
  testDepends = [ HUnit testFramework testFrameworkHunit time ];
  meta = {
    homepage = "http://github.com/pbrisbin/friendly-time";
    description = "Print time information in friendly ways";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
